### ISSUE TITLE
[readMe] Import naming

### ISSUE THREAD

**Issue by philohelp** [AryanJ-NYC/draft-js-aws-amplify-s3-plugin#4]
Hi there,

A quick word to say thanks for great job, it integrates nicely with my app.

Just a small remark concerning the readMe, it says:
`import createImagePlugin from 'draft-js-aws-amplify-s3-plugin';`
But then you have:
`const s3Plugin = createS3Plugin();`

Wishing you all the best

**Comment by AryanJ-NYC** [comment]
Thanks @philohelp! Nice catch.
